### PR TITLE
Revit_Core_Engine: Handled exceptions on obtaining ceiling pattern lines

### LINKED ISSUE #1201: Ceiling Issue with Revit Adapter Pull
#### Description:
Upon pulling a single ceiling, the pull works
Upon pulling multiple ceilings the following error(s) are thrown:

CeilingPullIssue

@alexissantella experienced this issue as well when pushing jsons of ceilings from Revit

@pawelbaran happy if this needs to be resolved in oM, felt like a Revit issue though!

#### Steps to reproduce:
Pull multiple ceilings

#### Expected behaviour:
All ceilings should pull

#### Test file(s):
The Revit file in this folder is the one we're using specifically:
[[(https://burohappold.sharepoint.com/sites/Direction/designtechnology/Presentation%20Library/Forms/AllItems.aspx?id=%2Fsites%2FDirection%2Fdesigntechnology%2FPresentation%20Library%2F220509%5FILFI%20Healthy%20Materials&viewid=1e550305%2D6bae%2D4408%2Daa47%2D4382a5155ad9)](https://burohappold.sharepoint.com/:u:/r/sites/Direction/designtechnology/Presentation%20Library/220509_ILFI%20Healthy%20Materials/ILFI%20Shoebox.rvt?csf=1&web=1&e=rrsf4e)]

### PR DESCRIPTION
**Pull request by vietle-bh**
### Issues addressed by this PR

Closes #1201 

Fixed the method for extracting pattern lines of a Revit ceiling being pulled. Also, added code for looking up a painted material if the compound structure's material doesn't have a surface pattern. This is based on ceilings in Kayleigh's test file which have painted materials.

### Test files

Same file Kayleigh sent us before but with one ceiling changed to the "GWB" type. The ceiling type triggered the issue, not the number of ceilings selected before the pull.
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Revit_Toolkit/Revit_Core_Engine-%231201-HandlePullingCeilingsWithoutValidMaterialPatterns?csf=1&web=1&e=bWOGJW

### Changelog

- Handled pulling ceilings where their surface patterns are painted or unavailable.

### CODE REVIEW

**Comment by vietle-bh** [comment]
@BHoMBot check required

File: Revit_Core_Engine/Query/CeilingPattern.cs [hunk 1]
```diff
@@ -68,6 +68,22 @@ public static List<BH.oM.Geometry.Line> CeilingPattern(this Ceiling ceiling, Rev
 
             double rotation;
             XYZ alignment = ceiling.CeilingPatternAlignment(material, settings, out rotation);
+            if (alignment == null)
+            {
+                // Try getting pattern of the main painted material if any
+                var paintedMaterialIds = ceiling.GetMaterialIds(true);
+                if (paintedMaterialIds.Count > 0)
+                {
+                    var mainPaintedId = paintedMaterialIds.Aggregate((id1, id2) => ceiling.GetMaterialArea(id1, true) > ceiling.GetMaterialArea(id2, true) ? id1 : id2);
```
Comment (pawelbaran) [inline Revit_Core_Engine/Query/CeilingPattern.cs:77]: What if there is more than 2 painted materials? Wouldn't it be better to combine `OrderByDescending` and `First` Linq queries here?

**Review by pawelbaran — CHANGES_REQUESTED** [review]
Looks good in general, minor tweaks suggested

File: Revit_Core_Engine/Query/CeilingPattern.cs (hunk 1 above)
Comment (vietle-bh) [reply Revit_Core_Engine/Query/CeilingPattern.cs:79]: Actually, I believe Aggregate here works with any number of materials. It will compare the first 2 materials, get one that is greater in area, compare that to the 3rd material, get the bigger one, and then continue like that till the end of the item list.

**Comment by vietle-bh** [comment]
@BHoMBot check required

File: Revit_Core_Engine/Query/CeilingPattern.cs (hunk 1 above)
Comment (pawelbaran) [reply Revit_Core_Engine/Query/CeilingPattern.cs:79]: Right, good point 👍

**Review by pawelbaran — APPROVED** [review]
Happy with the changes - it will capture a few edge cases while not making the existing ones any worse.

**Comment by vietle-bh** [comment]
> Happy with the changes - it will capture a few edge cases while not making the existing ones any worse.

Thanks 👍  Let's merge it!

**Comment by pawelbaran** [comment]
@BHoMBot check copyright-compliance
@BHoMBot check dataset-compliance
@BHoMBot check ready-to-merge
