### PR TITLE
FullCRUD renamed to FullPush and error handling fixes

### LINKED ISSUE #604: Revit_Toolkit: Rename PushType.FullCRUD to FullPush
#### Description

Following [BHoM Adapter #206](https://github.com/BHoM/BHoM_Adapter/issues/206)

### LINKED ISSUE #605: Align all CRUD methods to be `public` even if they are not direct overrides of base adapter ones
#### Broken rules:

As per title.

#### Suggestions to restore compliance:

As per title.

### LINKED ISSUE #606: Revit_Toolkit: NullReferenceException on adapter action when no document is open
#### Description:

When trying to push/pull without any document open in Revit, `GetListener` throws `NullReferenceException`. Would be nice to return a more informative error to the end user.

### LINKED ISSUE #607: Revit_Toolkit: NullReferenceException on adapter action when the adapter is inactive
#### Description:

When trying to push/pull with inactive Adapter, `NullReferenceException` is thrown. Would be nice to return a more informative error to the end user.

image

### PR DESCRIPTION
**Pull request by pawelbaran**
### NOTE: Depends on 

[BHoM Adapter #214](https://github.com/BHoM/BHoM_Adapter/pull/214)

   
### Issues addressed by this PR

Closes #604
Closes #605 
Closes #606 
Closes #607 

### Test files

[#604](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue604%2DFullPush)
#605 does not require a test file
[#606 and #607](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue606%2C607%2DNullReferenceHandlers)

### Changelog

- the code has been aligned to the change from `PushType.FullCRUD` to `PushType.FullPush`
- all `private` CRUD methods were made `public`
- `NullReferenceExceptions` occurring on inactive adapter and no open document in Revit were prevented and replaced with Errors recorded by Reflection
- Connection error message has been extended to make it more informative

### Additional comments
Although covering 4 issues, this PR is rather minimalistic. Happy to support in case of any issues with reviewing it.

### CODE REVIEW

File: Adapter_Revit_UI/AdapterActions/Push.cs [hunk 1]
```diff
@@ -63,9 +63,9 @@ public override List<object> Push(IEnumerable<object> objects, string tag = "",
             // If unset, set the pushType to AdapterSettings' value (base AdapterSettings default is FullCRUD). Disallow the unsupported PushTypes.
             if (pushType == PushType.AdapterDefault)
                 pushType = PushType.DeleteThenCreate;
-            else if (pushType == PushType.FullCRUD)
+            else if (pushType == PushType.FullPush)
             {
-                BH.Engine.Reflection.Compute.RecordError("Full CRUD is currently not supported by Revit_Toolkit, please use Create, UpdateOnly or DeleteThenCreate instead.");
+                BH.Engine.Reflection.Compute.RecordError("Full Push is currently not supported by Revit_Toolkit, please use Create, UpdateOnly or DeleteThenCreate instead.");
```
Comment (alelom) [inline Adapter_Revit_UI/AdapterActions/Push.cs]: 👍

**Comment by FraserGreenroyd** [comment]
@MajaLindroth can you take a look at this if you get chance, would be good to have a BEnv reviewer on this as well as Structures. Cheers :smile:
