### PR TITLE
Pull framing issues fixed

### LINKED ISSUE #882: Steel sections without material assigned pull as generic
#### Description:

When pulling a structural framing element, if the material has not been assigned, the resulting BHoM framing element has a material 'Unknown Steel Material' but the section is a generic, rather than a steel section. If we know it is steel, we should assign it a default steel material, so that at least it comes through as the proper section type.

#### Steps to reproduce:

Create some framing elements or columns in Revit, and don't assign the Structural Material. Pull these with BHoM and get AnalyticalBars - AnalyticalBars throws an error:
"The material with name Unknown Steel Material is not a valid structural material as it does not contain exactly one structural material fragment. An empty generic isotropic material has been assumed"

#### Expected behaviour:

Assign a default steel or concrete material (it can still be called Unknown Steel Material) rather than a material with no structural fragment.

### LINKED ISSUE #883: Library query on pulling framing/column elements to get material as well as profile, so that output is useful
#### Description:

Currently, Revit Toolkit first tries to look up the section name in the SectionProperties libraries, but it only grabs the profile from this library and ignores the material. Unless there is a specific material defined in Revit (perhaps run a library search on that, too), we should use the default material for that section, as listed in the library. Otherwise things are coming through as 'Unknown Steel Material' even though we know rectangular HSS (in the USA) use 46ksi steel by default.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #882
Closes #883

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue882%2C883%2DPullFramingIssues&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

### Changelog

- pull of material-specific sections without material assigned fixed to return material-specific BHoM `ISectionProperty`
- pull of bars fixed to keep the default material of `SectionProperty` loaded from library in case of failed material convert

### Additional comments

This PR should not overlap with any of the currently open PRs.

### CODE REVIEW

File: Revit_Core_Engine/Convert/Structure/FromRevit/Bars.cs [hunk 1]
```diff
@@ -103,12 +102,20 @@ public static List<Bar> BarsFromRevit(this FamilyInstance familyInstance, RevitS
...
+
                 property = BH.Engine.Structure.Create.SectionPropertyFromProfile(profile, materialFragment, profileName);
             }
             else
             {
                 property = property.GetShallowClone() as ISectionProperty;
-                property.Material = materialFragment;
+
+                if (!materialFound)
+                    BH.Engine.Reflection.Compute.RecordWarning($"Section property of a bar has been loaded from the library, but the material could not be converted. Default material of the section property has been used. Revit ElementId: {familyInstance.Id.IntegerValue}");
```
Comment (JosefTaylor) [inline Revit_Core_Engine/Convert/Structure/FromRevit/Bars.cs:115]: this sounds like the library material could not be converted, which to the average user sounds like a big problem. In fact, the likely case is that the user did not specify a material in Revit, which might not be a problem at all.

Comment (JosefTaylor) [inline Revit_Core_Engine/Convert/Structure/FromRevit/Bars.cs:115]:
```suggestion
                    BH.Engine.Reflection.Compute.RecordNote($"A matching section was found in the library. No valid material was defined in Revit, so the default material for this section was used. Revit ElementId: {familyInstance.Id.IntegerValue}");
```

**Review by JosefTaylor — COMMENTED** [review]
I will test to see under which conditions this warning comes up, but I think it does not need to be so dire.

**Comment by JosefTaylor** [comment]
While I was testing, I came across the following:
image
the error on pull is:

> 1. Failed to pull. Exception from the adapter: Method not found: 'Void BH.Adapter.BHoMAdapter.set_AdapterIdName(System.String)'.

I think this is a problem related to the recent adapter changes.

**Comment by IsakNaslundBh** [comment]
> the error on pull is:
>
>Failed to pull. Exception from the adapter: Method not found: 'Void BH.Adapter.BHoMAdapter.set_AdapterIdName(System.String)'.
I think this is a problem related to the recent adapter changes.

Yeah, that should be it. An update from master on this PR should hopefully resolve that issue!

**Comment by pawelbaran** [comment]
Description updated, hopefully the PR should be ready to merge guys 👍

**Review by JosefTaylor — APPROVED** [review]
Library sections with no material assigned are coming in with the default library material, yay!
sections with no material and no match in the library come in with unknown steel/concrete material, with correct SteelSection or ConcreteSection. Yay!

**Comment by FraserGreenroyd** [comment]
@BHoMBot check code compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check code compliance

**Comment by pawelbaran** [comment]
As discussed with @FraserGreenroyd, BHoMBot's compliance check can be ignored as it is complaining about the files not changed in this PR 👍

**Comment by FraserGreenroyd** [comment]
@BHoMBot check code compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check code compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check code compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check code compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check documentation compliance

**Comment by FraserGreenroyd** [comment]
@BHoMBot check copyright compliance

**Review by IsakNaslundBh — APPROVED** [review]
Works as expected
