### PR TITLE
Handle random order from `ConnectorManager.Connectors`

### LINKED ISSUE #1374: `ConnectorManager.Connectors` sometimes returns connectors in random orders
#### Description:

We discovered during beta testing that the call to `mepCurve.ConnectorManager.Connectors` doesn't always return connectors in the same order. This needs a fix to allow comparing objects for equality in unit tests.

#### Steps to reproduce:

Debugging the below will show the start and end point of the line switch positions randomly:
https://github.com/BHoM/Revit_Toolkit/blob/f22d01a54c418836931280b0a4d8610b2fb192bd/Revit_Core_Engine/Query/LocationCurve.cs#L174-L177

Connectors flipped

Another problem due to this bug is in calculating the orientation angle of an MEP curve:
https://github.com/BHoM/Revit_Toolkit/blob/f22d01a54c418836931280b0a4d8610b2fb192bd/Revit_Core_Engine/Query/OrientationAngle.cs#L79-L85

The same curve can report an angle of 360 or 0 degree, depending on which End connector Revit randomly sees first.

#### Expected behaviour:

We need to sort connectors consistently so that pulling the same object always produces:
- connectors in the same order 
- a consistent orientation angle value.

### PR DESCRIPTION
**Pull request by vietle-bh**
### Issues addressed by this PR

Closes #1374 

Used `SortCollinear` and its principle to sort connectors of an MEP curve based on their origin point locations.

### Test files

[SharePoint folder](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/Revit_Toolkit/%231375-HandleRandomConnectorsOrder?csf=1&web=1&e=4QgbKa)

- Use Revit 2020 or later
- Try pulling any cable tray by inputting its ID
- Check the output Json file after each pull to confirm every pull produces exactly the same result. In particular, check the start and end points of the element as well as its orientation angle.

image

### Changelog

Handle random order from `ConnectorManager.Connectors`

### CODE REVIEW

File: Revit_Core_Engine/Query/LocationCurve.cs [hunk 1]
```diff
@@ -173,7 +173,11 @@ public static List<BH.oM.Geometry.Line> LocationCurveMEP(this MEPCurve mepCurve,
             
             List<BH.oM.Geometry.Point> endPoints = connectors.Where(x => x.ConnectorType == ConnectorType.End).Select(x => x.Origin.PointFromRevit()).ToList();
             List<BH.oM.Geometry.Point> midPoints = connectors.Where(x => x.ConnectorType != ConnectorType.End).Select(x => x.Origin.PointFromRevit()).ToList();
-            
+
+            //Thanks to Revit, the order of connectors from connectorManager.Connectors isn't always the same!
```
Comment (FraserGreenroyd) [inline Revit_Core_Engine/Query/LocationCurve.cs:177]: 🤣 "Thanks to Revit"

**Review by michal-pekacki — APPROVED** [review]
I like the solution to this annoying problem, happy to approve 👍

**Comment by vietle-bh** [comment]
@BHoMBot check compliance
@BHoMBot check core
@BHoMBot check null-handling
@BHoMBot check serialisation

**Comment by vietle-bh** [comment]
@BHoMBot check versioning 
@BHoMBot check installer

**Comment by FraserGreenroyd** [comment]
@BHoMBot check ready-to-merge
