### PR TITLE
Curve push and convert bugs fixed

### LINKED ISSUE #807: Revit_Toolkit: model curves cannot be pushed with with ModelInstances
#### Description:

Cannot push model curves using `ModelInstance` objects - it just crashes.

### LINKED ISSUE #808: Revit_Toolkit: Curve conversion bugs
#### Description:

- ellipse `ToRevitCurves`
- two-noded `Polyline` `ToRevitCurve`
- single segment `PolyCurve` `ToRevitCurve`

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #807
Closes #808

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue808%2DCurveConvertBugs&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - can be run on an empty Revit file.

### Changelog

- pushing of Model Curves using `ModelInstance` reenabled
- BHoM => Revit curve convert bugs fixed for 2-noded `Polyline`, single-segment `PolyCurve` and `Ellipse`
- handling of Nurbs curves on Push slightly improved (could not get any better due to Revit limiations)

### CODE REVIEW

File: Revit_Core_Engine/Convert/Geometry/ToRevit/Curve.cs [hunk 1]
```diff
@@ -77,22 +77,36 @@ public static Curve ToRevit(this oM.Geometry.NurbsCurve curve)
...
+                case 1:
+                    return new oM.Geometry.Polyline { ControlPoints = curve.ControlPoints }.ToRevit();
+                case 2:
+                {
+                    BH.Engine.Reflection.Compute.RecordWarning("Revit does not support nurbs curves of degree 2. A simplified (possibly distorted) hermite spline has been created.");
+
+                    List<oM.Geometry.Point> cps = new List<oM.Geometry.Point>();
+                    for (int i = 0; i < curve.ControlPoints.Count; i++)
+                    {
+                        if (Math.Abs(1 - curve.Weights[i]) <= 1e-6)
```
Comment (LMarkowski) [inline Revit_Core_Engine/Convert/Geometry/ToRevit/Curve.cs:93]: Tolerance shouldn't be hard coded #536

Comment (pawelbaran) [reply Revit_Core_Engine/Convert/Geometry/ToRevit/Curve.cs:93]: Agreed - would you be happy with merging this PR and adding a todo item to #536 so that this did not get forgotten?
