### PR TITLE
Revit_Toolkit: Refactor of requests and RevitConfig

### LINKED ISSUE #364: Completely refactor Revit Requests
#### Broken rules:

As discussed here: https://github.com/BHoM/BHoM_UI/issues/121#issuecomment-528822108

Requests in Revit are improperly implemented and cause compliance issues. Consequently the menu is not structured as it should and Requests are difficult to find.

#### Suggestions to restore compliance:

1. All Revit requests should not be of type `FilterRequest`. That is a misuse of the `FilterRequest` type. They must be their own implementation of IRequest. So, for example, the `SelectionFilterRequest`:
https://github.com/BHoM/Revit_Toolkit/blob/003156a5d23c23ad46c24336eda4db16e75a9125/Revit_Engine/Create/FilterRequests/SelectionFilterRequest.cs#L37-L44
must be rewritten as composed by two parts:
     - a new `BH.oM.Revit` -> `SelectionRequest` class
     - a `BH.Engine.Revit.Create` method that returns a new `SelectionRequest`, much like the code above but without the use of FilterRequest.

2. The previous point must be done for all Revit Requests until no FilterRequest is left.

Note that all Requests must live under the Revit namespace as specified in point 1, unlike the current location under the "Adapters.Revit" namespace:
https://github.com/BHoM/Revit_Toolkit/blob/003156a5d23c23ad46c24336eda4db16e75a9125/Revit_Engine/Create/FilterRequests/SelectionFilterRequest.cs#L31
the "Adapters" part is wrong as we are in an Engine part of the code. You can't have both `Engine` and `Adapter` in the namespace, only Engine is correct in this case. 

@adecler @al-fisher please correct me if wrong / see if I missed anything

### LINKED ISSUE #487: Revit_Toolkit: Overhead on pull edges
#### Description:

It looks that there is no need to instantiate `elementTemp` as `element` variable could be used directly. Additionally, the edges can be queried only once for `element`, then assigned to every `iBHoMObject` with a `foreach` loop.

https://github.com/BHoM/Revit_Toolkit/blob/cd03243d6e1edcb0da6e8edde68589027cda8c6a/Adapter_Revit_UI/CRUD/Read.cs#L191-L202

### LINKED ISSUE #523: Revit_Toolkit: Fix reference CopyLocal, version and architecture
#### Broken rules:
Messy in a few .csproj files, an easy fix.

### PR DESCRIPTION
**Pull request by pawelbaran**
### NOTE: Depends on 

[BHoM #688](https://github.com/BHoM/BHoM/pull/688)
[BHoM_Engine #1460](https://github.com/BHoM/BHoM_Engine/pull/1460)
   
### Issues addressed by this PR

Closes #364
Closes #487
Closes #523

### Test files

On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue364%2DRefactorQueries).

### Changelog
- Approach to requests has been changed: `FilterRequests` have been replaced with case-specific IRequests
- Code that handles requests has been reviewed and optimized.
- `Read` methods of the Adapter and their dependen have been reviewed and simplified.

### Additional comments
This is a copy of #519 on a new branch.

### WARNING! THIS PR BREAKS ALL PREVIOUS SCRIPTS!
Because the code is being deleted instead of deprecated. As discussed with @al-fisher, it is justifiable to do that in this particular case as the changes proposed in this PR touch some core mechanics of the toolkit, including heave refactoring of Adapter's `Read` method, complete refactor of Requests, introduction of `RevitConfig` etc. Maintaining deprecated code would be much larger effort than required changes in the existing scripts (which are mainly replacements of the old request components with new ones).

Following the above, I am planning to use this occasion to push as many core changes as possible before the next Beta. These are:
- cleanup in naming #385  #517
- review/refactor of Push on the adapter side #448 #452
- further refactor of `RevitConfig` #514
- refactor of parameter mapping #256 #258 #451 #482
- centralization of some Revit-specific content #516

 Having done that I hope we will be able to stabilise the repo for some time at least.

### CODE REVIEW

**Comment by pawelbaran** [comment]
The PR passes the CI checks, we are good to go with the review! I will doubly appreciate your help this time since I would like to push a few more core changes in this milestone (as explained in the description).

**Comment by pawelbaran** [comment]
@kThorsager thanks for the comments! I have added my responses under each question.

> Errors should not be returned through the objects output.

This has been like that for a long time already - not subject of this PR.
> image
> 
> No error for not finding a specific index, should either denote how many failed or which weren't found

Good one! Fixed.
> image
> 
> Not sure if this is intended or not but pulling selected deselects the objects in revit.

Yeah, it has been like that for long due to the way in which Revit handles the external events. However, there might be a way to add an easy fix - will look into that later.
> 
> When pulling with category request, I'm getting three instances of one kind of wall, two types of construction,
> in Revit there are three defined categories
> It seems to me that this is either pulling one construction to much or to few, but I'm unsure of exactly what this should do.

Another good catch, but... Revit would not be Revit if it did what it says it does. Apparently, the wall of type _Stacked Wall_ falls into _Walls_ category, but its type (_Stacked Wall_) sits in... _Stacked Walls_ 🙈 So the code is actually correct, but Revit is a mess...
image


> image
> 
> This was a review of the test file

File: Adapter_Revit_UI/CRUD/Delete.cs [hunk 1]
```diff
@@ -54,7 +55,7 @@ public static bool Delete(IEnumerable<BHoMObject> bHoMObjects, Document document
             if (bHoMObjects.Count() < 1)
                 return false;
 
-            List<ElementId> elementIDList = Query.ElementIds(document, BH.Engine.Adapters.Revit.Query.UniqueIds(bHoMObjects, true), true);
+            List<ElementId> elementIDList = document.ElementIdsByUniqueIds(bHoMObjects.UniqueIds(true)).ToList();
```
Comment (alelom) [inline Adapter_Revit_UI/CRUD/Delete.cs]: Well done. Good to tidy up.

File: Adapter_Revit_UI/CRUD/Read.cs [hunk 2]
```diff
@@ -59,147 +61,115 @@ protected override IEnumerable<IBHoMObject> IRead(Type type, IList ids, ActionCo
...
-
-                    if (filterRequestElementIDs != null)
-                        filterRequestList.Add(filterRequestElementIDs);
-                }
-
             }
 
-            if(type != null)
+            if (elementIds.Count == 0 && uniqueIds.Count == 0)
+                return Read(new FilterRequest() { Type = type } as IRequest, actionConfig);
```
Comment (alelom) [inline Adapter_Revit_UI/CRUD/Read.cs]: The base adapter does already a similar thing in the Pull. If you specify only a Type in the request input, it will convert it into a FilterRequest with that type.
I don't know if you knew that. This is additional and does not hurt, but consider deleting it (or replacing it with an error message, like "no ids specified") if the other method works and you think is enough for you. 
Otherwise, leave this (no problem for me).

File: Engine_Revit_UI/Query/ElementIds/ElementIds.cs [hunk 3]
```diff
@@ -0,0 +1,231 @@
...
+using BH.Engine.Adapters.Revit;
+using BH.oM.Adapters.Revit;
+using BH.oM.Adapters.Revit.Enums;
+using BH.oM.Adapters.Revit.Interface;
+using BH.oM.Data.Requests;
+
+
+namespace BH.UI.Revit.Engine
+{
+    public static partial class Query
```
Comment (alelom) [inline Engine_Revit_UI/Query/ElementIds/ElementIds.cs]: Nice tidy up.

File: Engine_Revit_UI/Query/ElementIds/ElementIdsByInts.cs [hunk 4]
```diff
@@ -0,0 +1,63 @@
...
+    {
+        /***************************************************/
+        /****              Public methods               ****/
+        /***************************************************/
+
+        public static IEnumerable<ElementId> ElementIdsByInts(this Document document, List<int> elementIds, IEnumerable<ElementId> ids = null)
+        {
+            if (elementIds != null)
+            {
+                HashSet<int> corruptIds = new HashSet<int>(elementIds.Where(x => x < 0));
```
Comment (alelom) [inline Engine_Revit_UI/Query/ElementIds/ElementIdsByInts.cs]: Nice use of Hashset.

File: Engine_Revit_UI/Query/ElementIds/ElementIdsByUniqueIds.cs [hunk 5]
```diff
@@ -20,46 +20,60 @@
...
+using BH.Engine.Adapters.Revit;
+using BH.oM.Adapters.Revit;
+using BH.oM.Adapters.Revit.Enums;
+using BH.oM.Adapters.Revit.Interface;
 using BH.oM.Data.Requests;
-using System.ComponentModel;
-using BH.oM.Reflection.Attributes;
 
-namespace BH.Engine.Adapters.Revit
+namespace BH.UI.Revit.Engine
```
Comment (alelom) [inline Engine_Revit_UI/Query/ElementIds/ElementIdsByUniqueIds.cs]: Good

File: Revit_Adapter/AdapterActions/Pull.cs [hunk 6]
```diff
@@ -61,11 +61,11 @@ public override IEnumerable<object> Pull(IRequest request, PullType pullType = P
             if (!CheckConnection())
                 return new List<object>();
             
-            if (!(request is FilterRequest))
+            if (!(request is IRequest))
                 return new List<object>();
```
Comment (alelom) [inline Revit_Adapter/AdapterActions/Pull.cs]: This will never be true. You can remove the check.

Comment (alelom) [inline Revit_Adapter/AdapterActions/Pull.cs]: This will never be true. You can remove the check.

File: Revit_Adapter/AdapterActions/Pull.cs [hunk 7]
```diff
@@ -61,11 +61,11 @@ public override IEnumerable<object> Pull(IRequest request, PullType pullType = P
             if (!CheckConnection())
                 return new List<object>();
             
-            if (!(request is FilterRequest))
+            if (!(request is IRequest))
```
Comment (alelom) [inline Revit_Adapter/AdapterActions/Pull.cs]:
```suggestion

```

File: Revit_Adapter/AdapterActions/Pull.cs (hunk 6 above)
Comment (alelom) [inline Revit_Adapter/AdapterActions/Pull.cs]:
```suggestion

```

File: Revit_Engine/Create/Requests/ParameterIntegerRequest.cs [hunk 8]
```diff
@@ -0,0 +1,50 @@
...
+        /***************************************************/
+        /****              Public methods               ****/
+        /***************************************************/
+
+        [Description("Creates an IRequest that filters elements by given parameter value criterion.")]
+        [Input("parameterName", "Parameter name to be queried")]
+        [Input("numberComparisonType", "NumberComparisonType")]
+        [Input("value", "Parameter Value.")]
+        [Output("ParameterIntegerRequest")]
+        public static ParameterIntegerRequest ParameterIntegerRequest(string parameterName, NumberComparisonType numberComparisonType, int value)
```
Comment (alelom) [inline Revit_Engine/Create/Requests/ParameterIntegerRequest.cs]: Great job in creating all the new requests!

File: Adapter_Revit_UI/CRUD/Read.cs (hunk 2 above)
Comment (pawelbaran) [reply Adapter_Revit_UI/CRUD/Read.cs]: @alelom I had an issue with infinite loop here as far as I remember - this line (particularly casting to `IRequest` in order to call `BH.UI.Revit.Adapter.RevitUIAdapter.Read` instead of `BH.Adapter.BHoMAdapter.Read`) is meant to avoid it.

File: Revit_Engine/Create/Requests/WorksetRequest.cs [hunk 9]
```diff
@@ -0,0 +1,48 @@
...
+    public static partial class Create
+    {
+        /***************************************************/
+        /****              Public methods               ****/
+        /***************************************************/
+
+        [Description("Creates an IRequest that filters all elements in a given workset.")]
+        [Input("worksetName", "Workset Name")]
+        [Output("WorksetRequest")]
+        public static WorksetRequest WorksetRequest(string worksetName)
```
Comment (alelom) [inline Revit_Engine/Create/Requests/WorksetRequest.cs]: By the way, just to let you know if you didn't know:
If the Create method is "elementary" like this, we now have the automatic `Create` generator. So if your type is simple, you will automatically find in the UI the create method for it, without having to write an explicit Create.
It basically auto-generates a constructor that takes as an input all the public `{get;set;}` properties and populates them.

I dont think we haven't yet formulated what will happen to the "handwritten" Create method in the future. I heard Al mentioning that we will remove all of them to leave only the automatically generated one. 
However I personally think it's still good practice to write them as you did. So leave them in! :)

File: Revit_Adapter/AdapterActions/Pull.cs (hunk 6 above)
Comment (pawelbaran) [reply Revit_Adapter/AdapterActions/Pull.cs]: Fixed

File: Revit_Engine/Create/Requests/WorksetRequest.cs (hunk 9 above)
Comment (pawelbaran) [reply Revit_Engine/Create/Requests/WorksetRequest.cs]: Yeah, I have heard so too, and yeah, I do not know the exact plan too 🙊 So decided to add them, which also helped me to get my head around the problem better.

File: Adapter_Revit_UI/CRUD/Read.cs (hunk 2 above)
Comment (alelom) [reply Adapter_Revit_UI/CRUD/Read.cs]: Strange, I can't see neither how the infinite loop might happen, nor how this would solve that. Ok anyway

**Comment by FraserGreenroyd** [comment]
Adding `do-not-merge` while waiting for dependent PRs

File: Adapter_Revit_UI/Adapter_Revit_UI.csproj [hunk 10]
```diff
@@ -138,6 +138,10 @@
       <SpecificVersion>False</SpecificVersion>
       <HintPath>..\..\BHoM\Build\Common_oM.dll</HintPath>
     </Reference>
+    <Reference Include="Data_Engine, Version=3.0.0.0, Culture=neutral, processorArchitecture=MSIL">
```
Comment (FraserGreenroyd) [inline Adapter_Revit_UI/Adapter_Revit_UI.csproj]: Reference should not contain version, culture, or processor architecture

Comment (FraserGreenroyd) [inline Adapter_Revit_UI/Adapter_Revit_UI.csproj]: Reference should be set to `copy local = false`

File: Revit_oM/Revit_oM.csproj [hunk 11]
```diff
@@ -38,6 +38,11 @@
     <Reference Include="BHoM">
       <HintPath>..\..\BHoM\Build\BHoM.dll</HintPath>
     </Reference>
+    <Reference Include="Data_oM, Version=3.0.0.0, Culture=neutral, processorArchitecture=MSIL">
```
Comment (FraserGreenroyd) [inline Revit_oM/Revit_oM.csproj]: Reference should not contain version, culture, or processor architecture

File: Adapter_Revit_UI/Adapter_Revit_UI.csproj [hunk 12]
```diff
@@ -103,61 +103,74 @@
     <AssemblyName>Adapter_Revit_UI_2020</AssemblyName>
   </PropertyGroup>
   <ItemGroup>
-    <Reference Include="Adapter_Engine, Version=3.0.0.0, Culture=neutral, processorArchitecture=MSIL">
+    <Reference Include="Adapter_Engine, Version=3.0.0.0">
```
Comment (FraserGreenroyd) [inline Adapter_Revit_UI/Adapter_Revit_UI.csproj]: Don't need version here

File: Adapter_Revit_UI/Adapter_Revit_UI.csproj [hunk 13]
```diff
@@ -103,61 +103,74 @@
...
       <SpecificVersion>False</SpecificVersion>
       <HintPath>..\..\BHoM_Adapter\Build\Adapter_Engine.dll</HintPath>
       <Private>False</Private>
     </Reference>
-    <Reference Include="Adapter_oM, Version=3.0.0.0, Culture=neutral, processorArchitecture=MSIL">
+    <Reference Include="Adapter_oM, Version=3.0.0.0">
```
Comment (FraserGreenroyd) [inline Adapter_Revit_UI/Adapter_Revit_UI.csproj]: Don't need version here

**Comment by pawelbaran** [comment]
Following @FraserGreenroyd's comments, I have just raised #523 and resolved it here - the changes are only compliance, no functionality alteration.

File: Adapter_Revit_UI/Adapter_Revit_UI.csproj (hunk 10 above)
Comment (pawelbaran) [reply Adapter_Revit_UI/Adapter_Revit_UI.csproj]: Fixed

Comment (pawelbaran) [reply Adapter_Revit_UI/Adapter_Revit_UI.csproj]: Fixed

File: Revit_oM/Revit_oM.csproj (hunk 11 above)
Comment (pawelbaran) [reply Revit_oM/Revit_oM.csproj]: Fixed

File: Revit_Engine/Create/Requests/WorksetRequest.cs (hunk 9 above)
Comment (IsakNaslundBh) [reply Revit_Engine/Create/Requests/WorksetRequest.cs]: Would probably agree with @alelom s first comment. These wont be needed and are to be deprecated and then removed globally across all engines going forward, so would not add in new ones. Better then to move the descriptions to the object itself. @al-fisher

File: Adapter_Revit_UI/Adapter_Revit_UI.csproj (hunk 12 above)
Comment (pawelbaran) [reply Adapter_Revit_UI/Adapter_Revit_UI.csproj]: Fixed

File: Adapter_Revit_UI/Adapter_Revit_UI.csproj (hunk 13 above)
Comment (pawelbaran) [reply Adapter_Revit_UI/Adapter_Revit_UI.csproj]: Fixed

File: Revit_Engine/Create/Requests/WorksetRequest.cs (hunk 9 above)
Comment (al-fisher) [reply Revit_Engine/Create/Requests/WorksetRequest.cs]: Yes please! I would indeed move descriptions across to oM and remove any Creates with only defining primary BHoM properties as arguments. 
The object initializer syntax for any standard BHoM object with fully public get sets is now auto exposed in UI. Hope that is OK?

Comment (pawelbaran) [reply Revit_Engine/Create/Requests/WorksetRequest.cs]: Oke, I added descriptions to classes and deleted irrelevant Create methods.

**Comment by pawelbaran** [comment]
The PR is ready to merge on my end I believe.

**Comment by pawelbaran** [comment]
BTW, I have left the Create method for RevitConfig to avoid exposing `WrapNoNBHoMObjects` and `AllowHashForComparing` properties: 

image

**Comment by pawelbaran** [comment]
@kThorsager @alelom @FraserGreenroyd could you please re-approve (if you still like the changes)? Thank youu

**Comment by IsakNaslundBh** [comment]
Should mvoe out the `SelectionRequest` to main BHoM as can be used elsewhere as well, but have opened a separate issue for that to not hold this up

https://github.com/BHoM/Revit_Toolkit/issues/525
