### PR TITLE
Null check for familyLibrary in CategoryNames query method

### LINKED ISSUE #387: Revit_Adapter: code crashing when familyLibrary == null in CategoryNames query method
#### Description:
As in the description.

#### How to replicate:
Try to push the `ModelInstance` with incorrect family and type name.

#### Expected behaviour:

Do not crash but return an informative error.

#### Test file(s):
.gh test file located here.

### PR DESCRIPTION
**Pull request by pawelbaran**
### Issues addressed by this PR

Closes #387 

Null catch to prevent the code from crashing - instead an informative error is returned.

### Test files

Test file located [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?csf=1&e=WVbMGt&cid=7e1be85d%2D59b2%2D45f4%2D8d1b%2Da30668a3a29a&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FRevit%5FToolkit%2FRevit%5FToolkit%2DIssue387%2DCategoryNamesCrashOnNull).

### Changelog

Informative error given when requested family type does not exist in the Revit document.

### CODE REVIEW

File: Revit_Engine/Query/CategoryNames.cs [hunk 1]
```diff
@@ -41,7 +41,7 @@ public static partial class Query
         [Output("CategoryNames")]
         public static List<string> CategoryNames(this FamilyLibrary familyLibrary, string familyName, string familyTypeName = null)
         {
-            if (familyLibrary == null)
+            if (familyLibrary == null || familyLibrary.Dictionary == null)
```
Comment (FraserGreenroyd) [inline Revit_Engine/Query/CategoryNames.cs]: @pawelbaran am I missing something, but I can't see where this provides `Informative error given when requested family type does not exist in the Revit document`? I am probably missing something so just a comment, not a review :smile:

Comment (pawelbaran) [reply Revit_Engine/Query/CategoryNames.cs]: Oh how can you not see it 🙈 The warning about lack of matching type is triggered by some other part of the code that comes after that method call - it was already in place and seems to be working fine. Good catch though ;-)

Comment (FraserGreenroyd) [reply Revit_Engine/Query/CategoryNames.cs]: Fair enough @pawelbaran - just thought I'd check :smile: All good here!

**Comment by FraserGreenroyd** [comment]
Hi no problems from me, I had a query but it was resolved, happy for you to merge :smile:
